### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xnuts2** [SandaruKasa/Reaction-Userbot#1]
how to run it for all users?

**Comment by SandaruKasa** [comment]
That would be too spammy, but I think it's rather trivial to patch the code to do this.

**Comment by xnuts2** [comment]
> That would be too spammy, but I think it's rather trivial to patch the code to do this.

bruh I already did it myself after writing this question, just checked pyrogram documentation.I needed it for fun lol

**Comment by SandaruKasa** [comment]
Glad it worked :)
